### ISSUE TITLE
Chore: Respect Logging Pref of Parent/Supervisor App

### ISSUE THREAD

**Issue by nelsonic** [dwyl/envar#42]
As noted by @vans163 in https://github.com/dwyl/envar/pull/36#issuecomment-1332351311 our _current_ approach to logging 
is a little crude and could result in a lot of noise and potentially even perf issues on a high traffic app. 💭 

As highlighted in https://github.com/dwyl/envar/pull/36/files#diff-c24eb47ea99dc64a5109913f247d10fd83fa57e93cd9b4609cb703552215c901 there are 4 instances of `Logger` calls:

https://github.com/dwyl/envar/blob/03b035d9fd57254b65ae5db2d13552e5684a9c35/lib/envar.ex#L31-L33

https://github.com/dwyl/envar/blob/03b035d9fd57254b65ae5db2d13552e5684a9c35/lib/envar.ex#L55-L58

https://github.com/dwyl/envar/blob/03b035d9fd57254b65ae5db2d13552e5684a9c35/lib/envar.ex#L165-L170

https://github.com/dwyl/envar/blob/03b035d9fd57254b65ae5db2d13552e5684a9c35/lib/envar.ex#L199-L202

Most of these are conditional, i.e. they won't log if the variable is set or file exists.
But this last one ... I have to agree with @vans163 is sloppy. 🤦‍♂️ 

# Todo

+ [ ] Re-introduce `Logs` into the project but they should:
  + [ ] Be `OFF` by `default` i.e. not noisy! [they can be enabled on `:dev` or `:test`]
  + [ ] Respect the Logging level of the "parent" (e.g. `Phoenix`) App. 

# Side Quest:
