### ISSUE TITLE
`Envar.keys/1` should return the list of environment variable keys for an `.env` file

### ISSUE THREAD

**Issue by nelsonic** [dwyl/envar#9]
Recently, I found myself _manually_ writing out a list of environment variable names 
that are already described in an `.env` file ... 🙄 

This is a _horrible_ duplication and to be avoided! 

So I figure we could just _read_ the `.env` file and extract the `keys`. 
Similar to [`Object.keys`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) in `JS` land or [`Map.keys/1`](https://hexdocs.pm/elixir/1.12/Map.html#keys/1) here in `Elixir` world.

# Todo ✅ 

+ [ ] Create tests for what we expect to receive when parsing a sample `.env` file e.g: [`.env_sample`](https://github.com/dwyl/auth/blob/main/.env_sample) 📝 
+ [ ] Implement `Envar.keys/1` (and any helper) function(s) 🧑‍💻 
+ [ ] Publish new version of package to Hex.pm 📦 

I expect we can borrow some code from [`load/1`](https://github.com/dwyl/envar/blob/c04ebf1c389942ab909592b90c982a646054a90e/lib/envar.ex#L135) and simply return the keys. 💭  
(_or maybe refactor into a reusable helper function ..._)
(_so it should only take a few mins to implement this ..._ 🤞)
